name: flask_pipeline_1

on:
  push:
    branches:
      - main

jobs:
  python_app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setting up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirement.txt

      - name: Run the Flask app
        run: |
          python app.py &
          sleep 10

      - name: Test the Flask application
        run: |
          echo "Starting the test phase using curl command."
          curl http://127.0.0.1:5000
          echo "The testing has been completed!"
